spring.application.name=productos
spring.datasource.url=jdbc:mysql://localhost:3306/db_proyecto_prendas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8081
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Si quieres desactivar seguridad completamente (opcional)
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
